# Generated by Django 3.0.8 on 2022-08-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_userplaylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPlaylist',
        ),
    ]
