# Generated by Django 3.0.8 on 2022-08-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
