# Generated by Django 3.0.8 on 2022-08-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
    ]
